export enum Role {
  TODOS = '*',
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMINISTRADOR = 'ADMINISTRADOR',
  TECNICO = 'TECNICO',
  EMPRESARIO = 'EMPRESARIO',
  PUBLICADOR = 'PUBLICADOR',
  USUARIO_IOP = 'USUARIO_IOP',
  CONSULTA_BASICA = 'CONSULTA_BASICA',
  CONSULTA_AVANZADA = 'CONSULTA_AVANZADA',
  TECNICO_JURIDICO = 'TECNICO_JURIDICO',
  TECNICO_VENTANILLA = 'TECNICO_VENTANILLA',
}
